@extends('layouts.app')

@section('title', 'Таблица размеров')

@section('content')
    <div class="container container-my">


        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"> <a href="/" class="link breadcrumbs__link">Главная</a> </li>
                    <li class="breadcrumb-item"><a class="link breadcrumbs__link">Таблица размеров</a></li>
            </ol>
        </nav>


            <br>
            <h2 class=" text-center content__title">Таблица размеров</h2>
        <div class="text-center ">Как узнать размер нижнего белья?</div>
            <hr class="sep page__sep">

            <div class="container-fluid sizes">
                <div class="row proportions">
                    <div class="col-md-2">
                        <div class="title title--light">Выберите бренд:</div>
                        <div class=" proportions__nav">
                            @foreach ($brands as $brand)
                                <div class="list__item">
                                    <a class="link link--inherit" href="/sizes/{{$brand['url']}}.html">{{$brand['name_brand']}}</a>
                                </div>
                            @endforeach
                        </div>
                    </div>
                    <div class="col-md-10">

                        <div class="proportions__content">

                            <div class="proportions__question"><span>Есть вопросы?</span> Звоните
                                <a class="link link--text" href="tel:+74951338608">+7 (495) 133-86-08</a>
                            </div>
                            <div class="proportions__top">Российские размеры</div>




                            <h3 class="font-weight-bold">Размеры бюстгальтера</h3>
                            <table width="95%" border="1" cellpadding="0" cellspacing="0" align="center" class="razmer">
                                <colgroup><col> <col> <col> <col> <col> <col> <col></colgroup>
                                <tbody>
                                <tr>
                                    <td>
                                        Размер
                                    </td>
                                    <td>
                                        Eu
                                    </td>
                                    <td>
                                        65
                                    </td>
                                    <td>
                                        70
                                    </td>
                                    <td>
                                        75
                                    </td>
                                    <td>
                                        80
                                    </td>
                                    <td>
                                        85
                                    </td>
                                    <td>
                                        90
                                    </td>
                                    <td>
                                        95
                                    </td>
                                    <td>
                                        100
                                    </td>
                                    <td>
                                        105
                                    </td>
                                    <td>
                                        110
                                    </td>
                                    <td>
                                        115
                                    </td>
                                    <td>
                                        120
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        Обхват под грудью, точка 2 (см)
                                    </td>
                                    <td>
                                        63-67
                                    </td>
                                    <td>
                                        68-72
                                    </td>
                                    <td>
                                        73-77
                                    </td>
                                    <td>
                                        78-82
                                    </td>
                                    <td>
                                        83-87
                                    </td>
                                    <td>
                                        88-92
                                    </td>
                                    <td>
                                        93-97
                                    </td>
                                    <td>
                                        98-102
                                    </td>
                                    <td>
                                        103-107
                                    </td>
                                    <td>
                                        108-112
                                    </td>
                                    <td>
                                        113-117
                                    </td>
                                    <td>
                                        118-122
                                    </td>
                                </tr>
                                <tr>
                                    <td rowspan="10">
                                        Обхват груди, точка 1 (см)
                                    </td>
                                    <td>
                                        А
                                    </td>
                                    <td>
                                        77-79
                                    </td>
                                    <td>
                                        82-84
                                    </td>
                                    <td>
                                        87-89
                                    </td>
                                    <td>
                                        92-94
                                    </td>
                                    <td>
                                        97-99
                                    </td>
                                    <td>
                                        102-104
                                    </td>
                                    <td>
                                        107-109
                                    </td>
                                    <td>
                                        112-114
                                    </td>
                                    <td>
                                        117-119
                                    </td>
                                    <td>
                                        122-124
                                    </td>
                                    <td>
                                        -
                                    </td>
                                    <td>
                                        -
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        В
                                    </td>
                                    <td>
                                        79-81
                                    </td>
                                    <td>
                                        84-86
                                    </td>
                                    <td>
                                        89-91
                                    </td>
                                    <td>
                                        94-96
                                    </td>
                                    <td>
                                        99-101
                                    </td>
                                    <td>
                                        104-106
                                    </td>
                                    <td>
                                        109-111
                                    </td>
                                    <td>
                                        114-116
                                    </td>
                                    <td>
                                        119-121
                                    </td>
                                    <td>
                                        124-126
                                    </td>
                                    <td>
                                        129-131
                                    </td>
                                    <td>
                                        134-136
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        C
                                    </td>
                                    <td>
                                        81-83
                                    </td>
                                    <td>
                                        86-88
                                    </td>
                                    <td>
                                        91-93
                                    </td>
                                    <td>
                                        96-98
                                    </td>
                                    <td>
                                        101-103
                                    </td>
                                    <td>
                                        106-108
                                    </td>
                                    <td>
                                        111-113
                                    </td>
                                    <td>
                                        116-118
                                    </td>
                                    <td>
                                        121-123
                                    </td>
                                    <td>
                                        126-128
                                    </td>
                                    <td>
                                        131-133
                                    </td>
                                    <td>
                                        136-138
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        D
                                    </td>
                                    <td>
                                        83-85
                                    </td>
                                    <td>
                                        88-90
                                    </td>
                                    <td>
                                        93-95
                                    </td>
                                    <td>
                                        98-100
                                    </td>
                                    <td>
                                        103-105
                                    </td>
                                    <td>
                                        108-110
                                    </td>
                                    <td>
                                        113-115
                                    </td>
                                    <td>
                                        118-120
                                    </td>
                                    <td>
                                        123-125
                                    </td>
                                    <td>
                                        128-130
                                    </td>
                                    <td>
                                        133-135
                                    </td>
                                    <td>
                                        138-140
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        E
                                    </td>
                                    <td>
                                        85-87
                                    </td>
                                    <td>
                                        90-92
                                    </td>
                                    <td>
                                        95-97
                                    </td>
                                    <td>
                                        100-102
                                    </td>
                                    <td>
                                        105-107
                                    </td>
                                    <td>
                                        110-112
                                    </td>
                                    <td>
                                        115-117
                                    </td>
                                    <td>
                                        120-122
                                    </td>
                                    <td>
                                        125-127
                                    </td>
                                    <td>
                                        130-132
                                    </td>
                                    <td>
                                        135-137
                                    </td>
                                    <td>
                                        140-142
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        F
                                    </td>
                                    <td>
                                        87-89
                                    </td>
                                    <td>
                                        92-94
                                    </td>
                                    <td>
                                        97-99
                                    </td>
                                    <td>
                                        102-104
                                    </td>
                                    <td>
                                        107-109
                                    </td>
                                    <td>
                                        112-114
                                    </td>
                                    <td>
                                        117-119
                                    </td>
                                    <td>
                                        122-124
                                    </td>
                                    <td>
                                        127-129
                                    </td>
                                    <td>
                                        132-134
                                    </td>
                                    <td>
                                        137-139
                                    </td>
                                    <td>
                                        142-144
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        G
                                    </td>
                                    <td>
                                        89-91
                                    </td>
                                    <td>
                                        94-96
                                    </td>
                                    <td>
                                        99-101
                                    </td>
                                    <td>
                                        104-106
                                    </td>
                                    <td>
                                        109-111
                                    </td>
                                    <td>
                                        114-116
                                    </td>
                                    <td>
                                        119-121
                                    </td>
                                    <td>
                                        124-126
                                    </td>
                                    <td>
                                        129-131
                                    </td>
                                    <td>
                                        134-136
                                    </td>
                                    <td>
                                        139-141
                                    </td>
                                    <td>
                                        144-146
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        H
                                    </td>
                                    <td>
                                        91-93
                                    </td>
                                    <td>
                                        96-98
                                    </td>
                                    <td>
                                        101-103
                                    </td>
                                    <td>
                                        106-108
                                    </td>
                                    <td>
                                        111-113
                                    </td>
                                    <td>
                                        116-118
                                    </td>
                                    <td>
                                        121-123
                                    </td>
                                    <td>
                                        126-128
                                    </td>
                                    <td>
                                        131-133
                                    </td>
                                    <td>
                                        136-138
                                    </td>
                                    <td>
                                        141-143
                                    </td>
                                    <td>
                                        146-148
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        I
                                    </td>
                                    <td>
                                        93-95
                                    </td>
                                    <td>
                                        98-100
                                    </td>
                                    <td>
                                        103-105
                                    </td>
                                    <td>
                                        108-110
                                    </td>
                                    <td>
                                        113-115
                                    </td>
                                    <td>
                                        118-120
                                    </td>
                                    <td>
                                        123-125
                                    </td>
                                    <td>
                                        128-130
                                    </td>
                                    <td>
                                        133-135
                                    </td>
                                    <td>
                                        138-140
                                    </td>
                                    <td>
                                        143-145
                                    </td>
                                    <td>
                                        148-150
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        J
                                    </td>
                                    <td>
                                        95-97
                                    </td>
                                    <td>
                                        100-102
                                    </td>
                                    <td>
                                        105-107
                                    </td>
                                    <td>
                                        110-112
                                    </td>
                                    <td>
                                        115-117
                                    </td>
                                    <td>
                                        120-122
                                    </td>
                                    <td>
                                        125-127
                                    </td>
                                    <td>
                                        130-132
                                    </td>
                                    <td>
                                        135-137
                                    </td>
                                    <td>
                                        140-142
                                    </td>
                                    <td>
                                        145-147
                                    </td>
                                    <td>
                                        150-152
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                            <h2>Размеры трусов</h2>
                            <table width="95%" border="1" cellpadding="0" cellspacing="0" align="center" class="razmer">
                                <colgroup><col> <col> <col> <col> <col> <col> <col></colgroup>
                                <tbody>
                                <tr>
                                    <td>
                                        Размер
                                    </td>
                                    <td>
                                        90
                                    </td>
                                    <td>
                                        94
                                    </td>
                                    <td>
                                        98
                                    </td>
                                    <td>
                                        102
                                    </td>
                                    <td>
                                        106
                                    </td>
                                    <td>
                                        110
                                    </td>
                                    <td>
                                        114
                                    </td>
                                    <td>
                                        118
                                    </td>
                                    <td>
                                        122
                                    </td>
                                    <td>
                                        126
                                    </td>
                                    <td>
                                        130
                                    </td>
                                    <td>
                                        134
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Обхват бедер, точка 4 (см)
                                    </td>
                                    <td>
                                        88-92
                                    </td>
                                    <td>
                                        92-96
                                    </td>
                                    <td>
                                        96-100
                                    </td>
                                    <td>
                                        100-104
                                    </td>
                                    <td>
                                        104-108
                                    </td>
                                    <td>
                                        108-112
                                    </td>
                                    <td>
                                        112-116
                                    </td>
                                    <td>
                                        116-120
                                    </td>
                                    <td>
                                        120-124
                                    </td>
                                    <td>
                                        124-128
                                    </td>
                                    <td>
                                        128-132
                                    </td>
                                    <td>
                                        132-136
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                            <h2>Размеры купальников</h2>
                            <table width="95%" border="1" cellpadding="0" cellspacing="0" align="center" class="razmer">
                                <colgroup><col> <col> <col> <col> <col></colgroup>
                                <tbody>
                                <tr>
                                    <td>
                                        Размер купальника
                                    </td>
                                    <td>
                                        38
                                    </td>
                                    <td>
                                        40
                                    </td>
                                    <td>
                                        42
                                    </td>
                                    <td>
                                        44
                                    </td>
                                    <td>
                                        46
                                    </td>
                                    <td>
                                        48
                                    </td>
                                    <td>
                                        50
                                    </td>
                                    <td>
                                        52
                                    </td>
                                    <td>
                                        54
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Размер бюстгальтера
                                    </td>
                                    <td>
                                        70
                                    </td>
                                    <td>
                                        75
                                    </td>
                                    <td>
                                        80
                                    </td>
                                    <td>
                                        85
                                    </td>
                                    <td>
                                        90
                                    </td>
                                    <td>
                                        95
                                    </td>
                                    <td>
                                        100
                                    </td>
                                    <td>
                                        105
                                    </td>
                                    <td>
                                        110
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Размер чашки
                                    </td>
                                    <td colspan="9">
                                        Обхват груди, точка 1 – Обхват под грудью, точка 2 – Обхват бедер, точка 4 (см)
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        A
                                    </td>
                                    <td>
                                        83-70-96
                                    </td>
                                    <td>
                                        88-75-100
                                    </td>
                                    <td>
                                        93-80-104
                                    </td>
                                    <td>
                                        98-85-108
                                    </td>
                                    <td>
                                        103-90-112
                                    </td>
                                    <td>
                                        108-95-116
                                    </td>
                                    <td>
                                        113-100-120
                                    </td>
                                    <td>
                                        118-105-124
                                    </td>
                                    <td>
                                        123-110-128
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        B
                                    </td>
                                    <td>
                                        85-70-96
                                    </td>
                                    <td>
                                        90-75-100
                                    </td>
                                    <td>
                                        95-80-104
                                    </td>
                                    <td>
                                        100-85-108
                                    </td>
                                    <td>
                                        105-90-112
                                    </td>
                                    <td>
                                        110-95-116
                                    </td>
                                    <td>
                                        115-100-120
                                    </td>
                                    <td>
                                        120-105-124
                                    </td>
                                    <td>
                                        125-110-128
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        C
                                    </td>
                                    <td>
                                        87-70-96
                                    </td>
                                    <td>
                                        92-75-100
                                    </td>
                                    <td>
                                        97-80-104
                                    </td>
                                    <td>
                                        102-85-108
                                    </td>
                                    <td>
                                        107-90-112
                                    </td>
                                    <td>
                                        112-95-116
                                    </td>
                                    <td>
                                        117-100-120
                                    </td>
                                    <td>
                                        122-105-124
                                    </td>
                                    <td>
                                        127-110-128
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        D
                                    </td>
                                    <td>
                                        89-70-96
                                    </td>
                                    <td>
                                        94-75-100
                                    </td>
                                    <td>
                                        99-80-104
                                    </td>
                                    <td>
                                        104-85-108
                                    </td>
                                    <td>
                                        109-90-112
                                    </td>
                                    <td>
                                        114-95-116
                                    </td>
                                    <td>
                                        119-100-120
                                    </td>
                                    <td>
                                        124-105-124
                                    </td>
                                    <td>
                                        129-110-128
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        E
                                    </td>
                                    <td>
                                        91-70-96
                                    </td>
                                    <td>
                                        96-75-100
                                    </td>
                                    <td>
                                        101-80-104
                                    </td>
                                    <td>
                                        106-85-108
                                    </td>
                                    <td>
                                        111-90-112
                                    </td>
                                    <td>
                                        116-95-116
                                    </td>
                                    <td>
                                        121-100-120
                                    </td>
                                    <td>
                                        126-105-124
                                    </td>
                                    <td>
                                        131-110-128
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        F
                                    </td>
                                    <td>
                                        93-70-96
                                    </td>
                                    <td>
                                        98-75-100
                                    </td>
                                    <td>
                                        103-80-104
                                    </td>
                                    <td>
                                        108-85-108
                                    </td>
                                    <td>
                                        113-90-112
                                    </td>
                                    <td>
                                        118-95-116
                                    </td>
                                    <td>
                                        123-100-120
                                    </td>
                                    <td>
                                        128-105-124
                                    </td>
                                    <td>
                                        133-110-128
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        G
                                    </td>
                                    <td>
                                        95-70-96
                                    </td>
                                    <td>
                                        100-75-100
                                    </td>
                                    <td>
                                        105-80-104
                                    </td>
                                    <td>
                                        110-85-108
                                    </td>
                                    <td>
                                        115-90-112
                                    </td>
                                    <td>
                                        120-95-116
                                    </td>
                                    <td>
                                        125-100-120
                                    </td>
                                    <td>
                                        130-105-124
                                    </td>
                                    <td>
                                        135-110-128
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        H
                                    </td>
                                    <td>
                                        97-70-96
                                    </td>
                                    <td>
                                        102-75-100
                                    </td>
                                    <td>
                                        107-80-104
                                    </td>
                                    <td>
                                        112-85-108
                                    </td>
                                    <td>
                                        117-90-112
                                    </td>
                                    <td>
                                        122-95-116
                                    </td>
                                    <td>
                                        127-100-120
                                    </td>
                                    <td>
                                        132-105-124
                                    </td>
                                    <td>
                                        137-110-128
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        I
                                    </td>
                                    <td>
                                        99-70-96
                                    </td>
                                    <td>
                                        104-75-100
                                    </td>
                                    <td>
                                        109-80-104
                                    </td>
                                    <td>
                                        114-85-108
                                    </td>
                                    <td>
                                        119-90-112
                                    </td>
                                    <td>
                                        124-95-116
                                    </td>
                                    <td>
                                        129-100-120
                                    </td>
                                    <td>
                                        134-105-124
                                    </td>
                                    <td>
                                        139-110-128
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        J
                                    </td>
                                    <td>
                                        101-70-96
                                    </td>
                                    <td>
                                        106-75-100
                                    </td>
                                    <td>
                                        111-80-104
                                    </td>
                                    <td>
                                        116-85-108
                                    </td>
                                    <td>
                                        121-90-112
                                    </td>
                                    <td>
                                        126-95-116
                                    </td>
                                    <td>
                                        131-100-120
                                    </td>
                                    <td>
                                        136-105-124
                                    </td>
                                    <td>
                                        141-110-128
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                            <p>
                            </p>

                            <p>
                            </p>

                            <p style="text-align: center;">
                            </p>
                            <hr>
                            <p>
                            </p>
                        </div>

                        <div class="proportions__content">

                            <div class="proportions__gap">
                                <div class="proportions__schema">
                                    <div class="proportions__model">
                                        <img class="img loading" src="/image/girl.png" alt="" data-was-processed="true">
                                        <div class="proportions__pointer" data-point="1"></div>
                                        <div class="proportions__pointer" data-point="2"></div>
                                        <div class="proportions__pointer" data-point="3"></div>
                                        <div class="proportions__pointer" data-point="4"></div>
                                    </div>
                                    <div class="proportions__box" data-point="1">
                                        <p class="paragraph">Чтобы определить размер <b>чашки бюстгальтера</b>, вам необходимо замерить <b>обхват груди (ОГ)</b> <i>(см. точку № 1)</i> по наиболее выступающим точкам
                                        </p>
                                    </div>
                                    <div class="proportions__box" data-point="2">
                                        <p class="paragraph">Чтобы определить <b>основной размер бюстгальтера</b>, вам необходимо замерить <b>обхват под грудью (ОПГ)</b> <i>(см. точку № 2)</i>
                                        </p>
                                    </div>
                                    <div class="proportions__box" data-point="3">
                                        <p class="paragraph">Чтобы определить <b>размер трусиков</b>, вам необходимо замерить <b>обхват талии</b> <i>(см. точку № 3)</i>, а также <b>обхват бедер</b> <i>(см. точку № 4)</i> по наиболее выступающим точкам
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <p style="text-align: center;">
                                <b>Удачных покупок!</b>
                            </p>

                            <blockquote>
                                Остались вопросы? Звоните +7 (495) 133-86-08
                            </blockquote>



                        </div>

                    </div>
                </div>





            </div>


    </div>



@endsection
